# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_house_square_meters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='bathrooms',
            new_name='bath',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='bedrooms',
            new_name='bed',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='has_garage',
            new_name='garage',
        ),
    ]
